### ISSUE TITLE
Boost version issues

### ISSUE THREAD

**Issue by gxxzs** [parisChatz/yolo-online-learning#1]
I have tried to compile with three different versions of Boost, but I keep getting errors.

 Boost include path: /usr/local/boost/include

 Could not find the following Boost libraries:

          boost_signals

I also tried the  boost 1.53, however, another error occurs :

In file included from /usr/local/boost/include/boost/signals2/variadic_signal.hpp:21:0,
                 from /usr/local/boost/include/boost/signals2/signal.hpp:38,
                 from /usr/local/boost/include/boost/signals2.hpp:19,
                 from /opt/ros/kinetic/include/tf/tf.h:45,
                 from /opt/ros/kinetic/include/tf/transform_listener.h:38,
                 from /home/zs/yolo_lidar/src/yolo-online-learning/people/face_detector/src/face_detection.cpp:62:
/usr/local/boost/include/boost/signals2/detail/variadic_slot_invoker.hpp:84:46: error: expansion pattern ‘(<expression error> > args)’ contains no argument packs
           return func(std::get<indices>(args)...);
                                              ^
/usr/local/boost/include/boost/signals2/detail/variadic_slot_invoker.hpp: In member function ‘R boost::signals2::detail::call_with_tuple_args<R>::m_invoke(void*, Func&, boost::signals2::detail::unsigned_meta_array<indices ...>, boost::tuples::tuple<Args ...>) const’:
/usr/local/boost/include/boost/signals2/detail/variadic_slot_invoker.hpp:89:16: error: ‘get’ is not a member of ‘std’
           func(std::get<indices>(args)...);
                ^
/usr/local/boost/include/boost/signals2/detail/variadic_slot_invoker.hpp:89:16: note: suggested alternatives:
In file included from /opt/ros/kinetic/include/ros/ros.h:54:0,
                 from /home/zs/yolo_lidar/src/yolo-online-learning/people/face_detector/src/face_detection.cpp:45:
/opt/ros/kinetic/include/ros/param.h:465:18: note:   ‘ros::param::get’
 ROSCPP_DECL bool get(const std::string& key, std::map<std::string, bool>& map);
                  ^
In file included from /usr/local/boost/include/boost/tuple/tuple.hpp:33:0,
                 from /opt/ros/kinetic/include/message_filters/synchronizer.h:38,
                 from /opt/ros/kinetic/include/message_filters/time_synchronizer.h:38,
                 from /home/zs/yolo_lidar/src/yolo-online-learning/people/face_detector/src/face_detection.cpp:53:
/usr/local/boost/include/boost/tuple/detail/tuple_basic.hpp:211:1: note:   ‘boost::tuples::get’
 get(cons<HT, TT>& c BOOST_APPEND_EXPLICIT_TEMPLATE_NON_TYPE(int, N)) {
 ^
/usr/local/boost/include/boost/tuple/detail/tuple_basic.hpp:225:1: note:   ‘boost::tuples::get’
 get(const cons<HT, TT>& c BOOST_APPEND_EXPLICIT_TEMPLATE_NON_TYPE(int, N)) {
 ^
In file included from /usr/local/boost/include/boost/signals2/variadic_signal.hpp:21:0,
                 from /usr/local/boost/include/boost/signals2/signal.hpp:38,
                 from /usr/local/boost/include/boost/signals2.hpp:19,
                 from /opt/ros/kinetic/include/tf/tf.h:45,
                 from /opt/ros/kinetic/include/tf/transform_listener.h:38,
                 from /home/zs/yolo_lidar/src/yolo-online-learning/people/face_detector/src/face_detection.cpp:62:
/usr/local/boost/include/boost/signals2/detail/variadic_slot_invoker.hpp:89:39: error: expansion pattern ‘(<expression error> > args)’ contains no argument packs
           func(std::get<indices>(args)...);

This error seems like introduced by Boost too. Hence my question is which version would be work ?

**Comment by parisChatz** [comment]
Hmm, indeed it is possible that Boost introduces this error. I'm not sure which version could work but maybe try an older version.
